kind: pipeline
name: Container Test Application

steps:
- name: Static Analysis
  image: python
  - pip3 install -r reqs/analysis
  - python3 -m isort ctc
  - python3 -m black ctc --line-length=79
  - python3 -m flake8 ctc --verbose
  - python3 -m pylint ctc

