kind: pipeline
name: Development

steps:
- name: Static Analysis
  image: python:3.8-slim
  commands:
  - pip3 install -r reqs/analysis.txt
  - python3 -m isort src
  - python3 -m black src --line-length=79
  - python3 -m flake8 src --verbose

- name: Testing
  image: python:3.8-slim
  commands:
  - pip3 install -r reqs/testing.txt
  - cd src && python3 -m pytest tests/

- name: Build & Push
  image: plugins/docker
  settings:
    repo: alexpdr/ctc
    dockerfile: Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - main
    event:
    - push

- name: Pull Image & restart
  image: appleboy/drone-ssh
  settings:
    host: 
      from_secret: ssh_hostname
    user:
      from_secret: ssh_user
    password:
      from_secret: ssh_key
    port: 22
    script:
    - docker pull alexpdr/ctc:latest
    - docker-compose -f $SSH_PATH pull && docker-compose -f $SSH_PATH up
  environment:
    SSH_PATH:
      from_secret: ssh_path
  when:
    branch:
    - feature/ci-tweaks2
    event:
    - push
  depends_on:
    - Build & Push
