kind: pipeline
name: Development-Pipeline
type: docker

steps:
- name: Static Analysis
  image: python:3.8-slim
  commands:
  - pip3 install pip --upgrade
  - pip3 install -r reqs/analysis.txt
  - python3 -m isort src
  - python3 -m black src --line-length=79
  - python3 -m flake8 src --verbose

- name: Testing
  image: python:3.8-slim
  commands:
  - pip3 install -r reqs/testing.txt
  - cd src && python3 -m pytest tests/

- name: Build
  image: plugins/docker
  settings:
    repo: alexpdr/ctc
    dockerfile: Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - main
    event:
    - push

---
kind: pipeline
type: exec
name: Deployment-Pipeline

platform:
  os: linux
  arch: amd64

steps:
- name: Deploy
  commands:
  - echo ${DC_PATH}
  # - docker pull alexpdr/ctc:latest
  # - cd $${DC_PATH} && docker-compose pull && docker-compose up
  environment:
    DC_PATH:
      from_secret: dc_path