kind: pipeline
name: Development-Pipeline
type: docker

steps:
- name: Static Analysis
  image: python:3.8-slim
  commands:
  - pip3 install pip --upgrade
  - pip3 install -r reqs/analysis.txt
  - python3 -m isort src
  - python3 -m black src --line-length=79
  - python3 -m flake8 src --verbose

- name: Testing
  image: python:3.8-slim
  commands:
  - pip3 install -r reqs/testing.txt
  - cd src && python3 -m pytest tests/

- name: Build
  image: plugins/docker
  settings:
    repo: alexpdr/ctc
    dockerfile: Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - main
    event:
    - push

---
kind: pipeline
type: exec
name: Deployment-Pipeline

platform:
  os: linux
  arch: amd64

steps:
- name: Deploy
  image: appleboy/drone-ssh
  settings:
    host:
      from_secret: ssh_hostname
    port: 22
    username:
      from_secret: ssh_user
    key:
      from_secret: ssh_key
  commands:
  - docker pull alexpdr/ctc:latest
  - docker-compose -f $SSH_PATH pull && docker-compose -f $SSH_PATH up
  environment:
    SSH_PATH:
      from_secret: ssh_path